server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DBNAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
  instance:
    preferIpAddress: true
