server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: loancondition-service
          uri: lb://loancondition-service
          predicates:
            - Path=/api/mortgageLoanCondition/**
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/api/simulate/**
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/api/creditApplication/**
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/api/evaluation/**
        - id: status-service
          uri: lb://status-service
          predicates:
            - Path=/api/status/**
